Add post
putaindecode/putaindecode.io pull request #862
Opened 2021-02-13 14:27 UTC by bloodyowl

2021-02-13 16:04 UTC, MoOx approved these changes

2021-02-13 19:11 UTC, zoontek approved these changes

2021-02-14 17:20 UTC, jojmaht requested changes

2021-02-14 17:20 UTC, jojmaht commented on contents/articles/2021-02-15-le-vrai-probleme-des-web-components.md
> +specification.
```suggestion
spécification.
```

2021-02-14 17:20 UTC, jojmaht commented on contents/articles/2021-02-15-le-vrai-probleme-des-web-components.md
> +faible**, et un oubli est vite arrivé. Il peut difficile pour des outils de
```suggestion
faible**, et un oubli est vite arrivé. Il peut être difficile pour des outils de
```

2021-02-14 17:20 UTC, jojmaht commented on contents/articles/2021-02-15-le-vrai-probleme-des-web-components.md
> +maintenabilité qui limitaient ce qu'on est capable de produire sereinement.
Concordance des temps. "on se retrouverait => limiteraient" ou "on se retrouve => limitent"

2021-02-14 17:20 UTC, jojmaht commented on contents/articles/2021-02-15-le-vrai-probleme-des-web-components.md
> +"praticité" égale, ils n'unifient pas les frameworks, ils en contiennent.
Je mettrais du gras ici

2021-02-14 17:20 UTC, jojmaht commented on contents/articles/2021-02-15-le-vrai-probleme-des-web-components.md
> +sens d'une même entreprise perd alors un peu de sa superbe, puisqu'on duplique
```suggestion
sein d'une même entreprise perd alors un peu de sa superbe, puisqu'on duplique
```

2021-02-14 17:20 UTC, jojmaht commented on contents/articles/2021-02-15-le-vrai-probleme-des-web-components.md
> +que je n'utilise pas le bon composant adapté, ou que j'ai oublié de lui en
```suggestion
que je n'utilise pas le composant adapté, ou que j'ai oublié de lui en
```

2021-02-14 17:20 UTC, jojmaht commented on contents/articles/2021-02-15-le-vrai-probleme-des-web-components.md
> +d'éléments personnalisés a de grandes chances de m'empêcher d'en tirer un sens.
Un peu confuse cette phrase je trouve, la répétition de "sens" me paraît maladroite.

2021-02-14 17:20 UTC, jojmaht commented on contents/articles/2021-02-15-le-vrai-probleme-des-web-components.md
> +AMP ajoutant les roles `aria` qui vont bien au _runtime_, le serveur me renvoit
```suggestion
AMP ajoutant les roles `aria` qui vont bien au _runtime_, le serveur me renvoie
```

2021-02-14 17:20 UTC, jojmaht commented on contents/articles/2021-02-15-le-vrai-probleme-des-web-components.md
> +auxquels s'adressent les framework, ont quant à eux la tâche beaucoup plus
```suggestion
auxquels s'adressent les frameworks, ont quant à eux la tâche beaucoup plus
```

2021-02-14 17:20 UTC, jojmaht commented on contents/articles/2021-02-15-le-vrai-probleme-des-web-components.md
> +**retro-compatibilité**, sans pour autant empêcher les **évolutions futures**.
```suggestion
**rétro-compatibilité**, sans pour autant empêcher les **évolutions futures**.
```

2021-02-14 17:20 UTC, jojmaht commented on contents/articles/2021-02-15-le-vrai-probleme-des-web-components.md
> +En se foutant royalement du concessus (qui aurait eu de fortes de chances de
```suggestion
En se foutant royalement du consensus (qui aurait eu de fortes de chances de
```

2021-02-14 17:20 UTC, jojmaht commented on contents/articles/2021-02-15-le-vrai-probleme-des-web-components.md
> +l'adoption que l'entreprise s'est efforcée de lancer à grands coups de
```suggestion
adoption que l'entreprise s'est efforcée de lancer à grands coups de
```

2021-02-14 18:07 UTC, merged